### ISSUE TITLE
Review 08 Linter and create readme_es.md

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/parcel-by-sample#10]
Go through the steps, try to reproduce the sample, if you find any issue report, if you find typos or text not well written, then crate a readme_es.md version, just fork it and PR :)

This sample needs additional completion (check webpack 4 by sample linter)

**Comment by PedroJesusRomeroOrtega** [comment]
Hi @brauliodiez !
I see that in Webpack4 sample you use babel-eslint parser and put some rules to .eslintrc.json file.
I will put that in this example; agree?
And I think is better to use students.js and averageService.js instead of index.js to have a more complete example,ok?

**Comment by brauliodiez** [comment]
Great idea !!!

Add the needed steps to the sample.
